import type { ProviderEndpointManifestEntry } from "../providerTypes";

const unimplementedNote =
  "Documented official endpoint. Request builder, response parser, and unit test are not implemented, so this capability is intentionally disabled.";

const pixverseOfficialEndpoints: Omit<ProviderEndpointManifestEntry, "baseUrlEnvKey">[] = [
  {
    id: "pixverse_official_text_to_video",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/text/generate",
    docsUrl: "https://docs.platform.pixverse.ai/text-to-video-generation-13016634e0",
    capability: "text_to_video",
    authRequired: true,
    requestSchema:
      "{ aspect_ratio, duration, model, prompt, quality, motion_mode?, camera_movement?, seed?, template_id? }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_image_to_video",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/img/generate",
    docsUrl: "https://docs.platform.pixverse.ai/image-to-video-generation-13016633e0",
    capability: "image_to_video",
    authRequired: true,
    requestSchema:
      "{ img_id, prompt, model, duration, quality, aspect_ratio?, motion_mode?, negative_prompt? }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: true,
    stability: "official",
    notes: "Implemented with request builder, response parser, and unit coverage."
  },
  {
    id: "pixverse_official_template_video",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/img/generate",
    docsUrl: "https://docs.platform.pixverse.ai/template-video-generation-33889423e0",
    capability: "template_video",
    authRequired: true,
    requestSchema: "{ img_id, duration, model, prompt, quality, template_id }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_transition",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/transition/generate",
    docsUrl: "https://docs.platform.pixverse.ai/transitionfirst-last-frame-generation-15123014e0",
    capability: "transition_video",
    authRequired: true,
    requestSchema:
      "{ prompt, model, duration, quality, first_frame_img, last_frame_img, motion_mode?, sound_effect_switch?, lip_sync_tts_speaker_id?, lip_sync_tts_content?, seed? }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_lip_sync",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/lip_sync/generate",
    docsUrl: "https://docs.platform.pixverse.ai/speechlipsync-generation-19094278e0",
    capability: "lip_sync",
    authRequired: true,
    requestSchema:
      "{ source_video_id?|video_media_id?, audio_media_id?|tts_speaker_id?+tts_content? }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_lip_sync_tts_list",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "GET",
    path: "/openapi/v2/video/lip_sync/tts_list",
    docsUrl: "https://docs.platform.pixverse.ai/get-speechlipsync-tts-list-19094355e0",
    capability: "lip_sync_tts_list",
    authRequired: true,
    requestSchema: "headers only",
    responseSchema: "{ ErrCode, ErrMsg, Resp: [{ id, name, ... }] }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_fusion",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/fusion/generate",
    docsUrl: "https://docs.platform.pixverse.ai/fusionreference-to-video-generation-19884194e0",
    capability: "fusion_video",
    authRequired: true,
    requestSchema:
      "{ duration, quality, aspect_ratio, camera_movement, model, motion_mode, prompt, img_id_list: [{ img_id, name }], sound_effect_switch, sound_effect_content? }",
    responseSchema: "Official docs response example is incomplete; verify before implementation.",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_multi_transition",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/transition/generate",
    docsUrl: "https://docs.platform.pixverse.ai/multi-transition-video-generation-24001841e0",
    capability: "multi_transition_video",
    authRequired: true,
    requestSchema: "{ duration, quality, seed, aspect_ratio, style, image_list: [img_id, ...] }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_restyle",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/restyle/generate",
    docsUrl: "https://docs.platform.pixverse.ai/restyle-video-generation-21992681e0",
    capability: "restyle_video",
    authRequired: true,
    requestSchema: "{ video_id, style }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_restyle_effect_list",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "GET",
    path: "/openapi/v2/video/restyle/get_style_list",
    docsUrl: "https://docs.platform.pixverse.ai/restyle-effect-list-21992862e0",
    capability: "restyle_effect_list",
    authRequired: true,
    requestSchema: "headers only",
    responseSchema: "Official docs response example is incomplete; verify before implementation.",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_swap_mask",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/swap/generate_mask",
    docsUrl: "https://docs.platform.pixverse.ai/swap-mask-generation-24001877e0",
    capability: "swap_mask",
    authRequired: true,
    requestSchema: "multipart/form-data { source_video_id, target_image }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { mask_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_swap_video",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/swap/generate_video",
    docsUrl: "https://docs.platform.pixverse.ai/swap-video-generation-24001839e0",
    capability: "swap_video",
    authRequired: true,
    requestSchema: "{ source_video_id, target_mask_id, swap_image_id }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_sound_effect",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/sound_effect/generate",
    docsUrl: "https://docs.platform.pixverse.ai/sound-effect-generation-19884196e0",
    capability: "sound_effect",
    authRequired: true,
    requestSchema: "{ video_id, prompt }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_extend",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/extend/generate",
    docsUrl: "https://docs.platform.pixverse.ai/extend-generation-19094393e0",
    capability: "extend_video",
    authRequired: true,
    requestSchema: "{ video_id, prompt }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_video_status",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "GET",
    path: "/openapi/v2/video/result/{id}",
    docsUrl: "https://docs.platform.pixverse.ai/get-video-generation-status-13016632e0",
    capability: "video_status",
    authRequired: true,
    requestSchema: "path { id }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { id, status, url?, create_time? } }",
    implemented: true,
    stability: "official",
    notes: "Implemented with request builder, response parser, and unit coverage."
  },
  {
    id: "pixverse_official_motion_control_mimic",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/motion-control/generate",
    docsUrl: "https://docs.platform.pixverse.ai/motion-control-mimic-generation-28748523e0",
    capability: "motion_control",
    authRequired: true,
    requestSchema: "{ video_id, img_id, model, quality }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_modify",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/video/modify/generate",
    docsUrl: "https://docs.platform.pixverse.ai/modify-generation-33365578e0",
    capability: "modify_video",
    authRequired: true,
    requestSchema: "{ video_id, prompt, model, duration?, quality? }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { video_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_image_template",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/image/generation",
    docsUrl: "https://docs.platform.pixverse.ai/image-template-generation-27564921e0",
    capability: "image_template",
    authRequired: true,
    requestSchema: "{ template_id, images: [img_id, ...] }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { image_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_image_status",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "GET",
    path: "/openapi/v2/image/result/{id}",
    docsUrl: "https://docs.platform.pixverse.ai/get-image-generation-27565028e0",
    capability: "image_status",
    authRequired: true,
    requestSchema: "path { id }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { id, status, url? } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  },
  {
    id: "pixverse_official_upload_image",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/image/upload",
    docsUrl: "https://docs.platform.pixverse.ai/upload-image-13016631e0",
    capability: "upload_image",
    authRequired: true,
    requestSchema: "multipart/form-data { image }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { img_id, img_url } }",
    implemented: true,
    stability: "official",
    notes: "Implemented with request builder, response parser, and unit coverage."
  },
  {
    id: "pixverse_official_credit_balance",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "GET",
    path: "/openapi/v2/account/balance",
    docsUrl: "https://docs.platform.pixverse.ai/get-user-credit-balance-13778989e0",
    capability: "credit_balance",
    authRequired: true,
    requestSchema: "headers only",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { account_id, credit_monthly, credit_package } }",
    implemented: true,
    stability: "official",
    notes: "Implemented with request builder, response parser, and unit coverage."
  },
  {
    id: "pixverse_official_media_upload",
    providerId: "pixverse_official_api",
    providerGroup: "pixverse",
    providerSource: "official_api",
    method: "POST",
    path: "/openapi/v2/media/upload",
    docsUrl: "https://docs.platform.pixverse.ai/upload-videoaudio-19094225e0",
    capability: "media_upload",
    authRequired: true,
    requestSchema: "multipart/form-data { media: video|audio }",
    responseSchema: "{ ErrCode, ErrMsg, Resp: { media_id } }",
    implemented: false,
    stability: "official",
    notes: unimplementedNote
  }
];

export const pixverseOfficialEndpointManifest: ProviderEndpointManifestEntry[] = pixverseOfficialEndpoints.map((endpoint) => ({
  ...endpoint,
  baseUrlEnvKey: "PIXVERSE_OFFICIAL_BASE_URL"
}));
