import { ProviderEndpointManifestEntry } from "@/lib/providers/providerTypes";

export const pixverseWebObservedEndpointManifest: ProviderEndpointManifestEntry[] = [
  {
    "id": "pixverse_web_unknown_768d7167e1",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/manifest.webmanifest",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/manifest+json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"id\":\"string\",\"name\":\"string\",\"short_name\":\"string\",\"description\":\"string\",\"start_url\":\"string\",\"scope\":\"string\",\"display\":\"string\",\"orientation\":\"string\",\"theme_color\":\"string\",\"background_color\":\"string\",\"categories\":[\"string\"],\"related_applications\":[{\"platform\":\"string\",\"url\":\"string\"}],\"prefer_related_applications\":\"boolean\",\"icons\":[{\"src\":\"string\",\"sizes\":\"string\",\"type\":\"string\",\"purpose\":\"string\"}],\"shortcuts\":[]}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_f35e68ffd9",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/ccm/collect",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "www.google.com",
    "queryShape": "ae, apvc, apve, apvf, auid, dl, dma, dr, dt, en, ep.ads_data_redaction, frm, gcd, gtm, navt, npa, rcb, rnd, scrsrc, tag_exp, tfd, tft",
    "requestContentType": "",
    "responseContentType": "text/plain",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 4,
    "sanitizedRequestShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"body\":\"undefined\",\"mimeType\":\"undefined\",\"params\":\"undefined\"},\"query\":{\"ae\":\"string\",\"apvc\":\"string\",\"apve\":\"string\",\"apvf\":\"string\",\"auid\":\"string\",\"dl\":\"string\",\"dma\":\"string\",\"dr\":\"string\",\"dt\":\"string\",\"en\":\"string\",\"ep.ads_data_redaction\":\"string\",\"frm\":\"string\",\"gcd\":\"string\",\"gcs\":\"string\",\"gtm\":\"string\",\"navt\":\"string\",\"npa\":\"string\",\"rcb\":\"string\",\"rnd\":\"string\",\"scrsrc\":\"string\",\"tag_exp\":\"string\",\"tfd\":\"string\",\"tft\":\"string\",\"tid\":\"string\",\"tids\":\"string\"}}",
    "sanitizedResponseShape": "{\"content\":{\"body\":\"undefined\",\"mimeType\":\"string\"},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}]}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_407a70029c",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/rmkt/collect/{id}/",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "www.google.com",
    "queryShape": "async, auid, bg, cv, data, dma, en, fmt, frm, fst, gcd, gcp, gtm, guid, hn, npa, pscdl, random, rcb, ref, tag_exp, tiba, u_h, u_w, url",
    "requestContentType": "",
    "responseContentType": "text/html",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 4,
    "sanitizedRequestShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"body\":\"undefined\",\"mimeType\":\"undefined\",\"params\":\"undefined\"},\"query\":{\"ae\":\"string\",\"async\":\"string\",\"auid\":\"string\",\"bg\":\"string\",\"cv\":\"string\",\"data\":\"string\",\"dma\":\"string\",\"en\":\"string\",\"fmt\":\"string\",\"frm\":\"string\",\"fst\":\"string\",\"gcd\":\"string\",\"gcp\":\"string\",\"gtm\":\"string\",\"guid\":\"string\",\"hn\":\"string\",\"npa\":\"string\",\"pscdl\":\"string\",\"random\":\"string\",\"rcb\":\"string\",\"ref\":\"string\",\"tag_exp\":\"string\",\"tiba\":\"string\",\"u_h\":\"string\",\"u_w\":\"string\",\"url\":\"string\"}}",
    "sanitizedResponseShape": "{\"content\":{\"body\":\"undefined\",\"mimeType\":\"string\"},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}]}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_360075796b",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/pagead/conversion/{id}/",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "www.googleadservices.com",
    "queryShape": "_tu, async, auid, bg, bttype, capi, category, cv, dma, ec_mode, em, en, fmt, frm, fst, gcd, gcl_ctr, gcs, gtm, guid, hn, label, npa, pscdl, random, rcb, ref, tag_exp, tiba, u_h, u_w, url, value",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{\"random\":\"string\",\"cv\":\"string\",\"fst\":\"string\",\"fmt\":\"string\",\"bg\":\"string\",\"guid\":\"string\",\"async\":\"string\",\"en\":\"string\",\"gtm\":\"string\",\"gcs\":\"string\",\"gcd\":\"string\",\"dma\":\"string\",\"tag_exp\":\"string\",\"u_w\":\"string\",\"u_h\":\"string\",\"url\":\"string\",\"ref\":\"string\",\"rcb\":\"string\",\"label\":\"string\",\"capi\":\"string\",\"frm\":\"string\",\"tiba\":\"string\",\"bttype\":\"string\",\"value\":\"string\",\"hn\":\"string\",\"npa\":\"string\",\"pscdl\":\"string\",\"auid\":\"string\",\"ec_mode\":\"string\",\"_tu\":\"string\",\"gcl_ctr\":\"string\",\"category\":\"string\",\"em\":\"string\"},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"event: message\\ndata: {\\\"fetch\\\":[\\\"https://googleads.g.doubleclick.net/pagead/viewthroughconversion/11411307723/?random\":\"string\",\"cv\":\"string\",\"fst\":\"string\",\"fmt\":\"string\",\"bg\":\"string\",\"guid\":\"string\",\"async\":\"string\",\"en\":\"string\",\"gtm\":\"string\",\"gcs\":\"string\",\"gcd\":\"string\",\"dma\":\"string\",\"tag_exp\":\"string\",\"u_w\":\"string\",\"u_h\":\"string\",\"url\":\"string\",\"ref\":\"string\",\"rcb\":\"string\",\"label\":\"string\",\"capi\":\"string\",\"frm\":\"string\",\"tiba\":\"string\",\"value\":\"string\",\"hn\":\"string\",\"npa\":\"string\",\"pscdl\":\"string\",\"auid\":\"string\",\"ec_mode\":\"string\",\"_tu\":\"string\",\"gcl_ctr\":\"string\",\"category\":\"string\",\"em\":\"string\",\"ct_cookie_present\":\"string\",\"crd\":\"string\",\"cerd\":\"string\",\"eitems\":\"string\",\"fsk\":\"string\",\"pscrd\":\"string\",\"gcp\":\"string\"}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_config_2339f731dc",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/creative_platform/config",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "application/json",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "config",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"string\",\"params\":[],\"body\":{\"data\":[{\"data_id\":\"string\"}]}}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"data\":[{\"data_id\":\"string\",\"value\":\"string\"}]}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_credit_balance_90d1b134a6",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/config/ad_credits",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "credit_balance",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "credit_balance",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"ad_open\":\"boolean\",\"ad_open_limit\":\"number\",\"ad_openFreq\":\"number\",\"ad_open_type\":\"string\",\"ad_open_trigger\":\"number\",\"ad_open_overtime\":\"number\",\"ad_open_gap\":\"number\",\"ad_reward\":\"boolean\",\"ad_reward_limit\":\"number\",\"ad_reward_limit_ab_test_enable\":\"boolean\",\"ad_banner\":\"boolean\",\"ad_interstitial\":\"boolean\",\"ad_interstitial_limit\":\"number\",\"register_credits\":\"number\",\"daily_credits\":\"number\",\"ad_reward_no_water\":\"boolean\",\"ad_reward_no_water_limit\":\"number\",\"ad_reward_hd\":\"boolean\",\"ad_reward_hd_limit\":\"number\",\"is_free\":\"boolean\",\"creation_for_free\":{\"drama_model_free\":\"boolean\",\"extend\":\"boolean\",\"v56_model_free\":\"boolean\"},\"ad_banner_home_page\":\"boolean\",\"ad_banner_home_page_order\":\"number\",\"ad_banner_home_page_fre\":\"number\",\"ad_feed_home_page\":\"boolean\",\"ad_feed_home_page_start\":\"number\",\"ad_feed_home_page_fre\":\"number\",\"ad_create_page_enable\":\"boolean\",\"ad_banner_create_page\":\"boolean\",\"ad_reward_get_sub_enable\":\"boolean\"}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_task_list_db73f48552",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/task/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "task_list",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":[{\"name\":\"string\",\"platform\":\"number\",\"task_type\":\"number\",\"sub_type\":\"number\",\"reward\":\"number\",\"progress\":\"number\",\"total_counts\":\"number\",\"completed_counts\":\"number\",\"expired_time\":\"string\",\"is_double\":\"boolean\",\"multiplier\":\"number\"}]}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_18200577b9",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/invite/bonus/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"invite_list\":[{\"node_number\":\"number\",\"reward_credits\":\"number\",\"claim_status\":\"number\"}],\"invite_numbers\":\"number\",\"invite_completed_node_num\":\"number\",\"invite_finish_time\":\"string\",\"invite_completed_credits\":\"number\",\"new_round_init\":\"number\",\"account_id\":\"number\",\"change_by_round\":\"boolean\"}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_user_profile_be9d38739b",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/creative_platform/invite/account/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "application/json",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "user_profile",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"string\",\"params\":[],\"body\":{}}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"items\":[{\"account_id\":\"number\",\"account_avatar\":\"string\",\"nick_name\":\"string\",\"register_at\":\"string\",\"followed\":\"boolean\",\"user_name\":\"string\"}],\"total\":\"number\",\"next_offset\":\"number\"}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_90a6b14316",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/creative_platform/internal_message/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "application/json",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"string\",\"params\":[],\"body\":{\"Offset\":\"number\",\"Limit\":\"number\"}}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"list\":[{\"id\":\"number\",\"title\":\"string\",\"content\":\"string\",\"brief\":\"string\",\"thumbnail_url\":\"string\",\"send_time\":\"string\",\"is_read\":\"boolean\"}],\"total\":\"number\",\"next_offset\":\"number\",\"has_unread\":\"boolean\"}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_cd92a1ef12",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/creative_platform/asset/library/models",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "application/json",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"string\",\"params\":[],\"body\":{\"tab\":\"string\",\"filter\":{\"start_time\":\"number\",\"end_time\":\"number\"}}}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"models\":[\"string\"]}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_user_profile_33c9a15710",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/getUserInfo",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "user_profile",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"AccId\":\"number\",\"AccountId\":\"number\",\"Username\":\"string\",\"Mail\":\"string\",\"HasPassword\":\"boolean\",\"Img\":\"string\",\"DiscordUserName\":\"string\",\"Email\":\"[REDACTED]\",\"Nickname\":\"string\",\"Gender\":\"number\",\"PhoneNum\":\"string\",\"DiscordUserId\":\"string\",\"Price\":\"number\",\"PremiumType\":\"number\",\"BillingPeriod\":\"string\",\"ExpireDate\":\"number\",\"FastQuota\":\"number\",\"UsedFastQuota\":\"number\",\"FastBonusQuota\":\"number\",\"UsedFastBonusQuota\":\"number\",\"Gmail\":\"string\",\"Subscription\":\"number\",\"MemberType\":\"number\",\"avatar\":\"string\",\"desc\":\"string\",\"encrypted\":\"string\",\"invite_code\":\"string\",\"is_creator\":\"boolean\",\"register_country\":\"string\"}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_f41ed17098",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/team/workspace/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"active_workspace_id\":\"number\",\"pending_subscription\":\"object\",\"workspaces\":[{\"workspace_id\":\"number\",\"name\":\"string\",\"avatar\":\"string\",\"type\":\"string\",\"role\":\"string\",\"role_level\":\"number\",\"member_count\":\"number\",\"seat_count\":\"number\",\"subscription_status\":\"string\",\"credits\":\"number\",\"created_at\":\"string\"}]}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_asset_library_bd75a2ebee",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/creative_platform/asset/library/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "application/json",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "asset_library",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"string\",\"params\":[],\"body\":{\"tab\":\"string\",\"asset_source\":\"number\",\"folder_id\":\"number\",\"offset\":\"number\",\"limit\":\"number\",\"sort_order\":\"string\",\"filter\":{\"start_time\":\"number\",\"end_time\":\"number\"},\"current\":\"number\",\"web_offset\":\"number\",\"app_offset\":\"number\"}}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"app_has_more\":\"boolean\",\"app_next_offset\":\"number\",\"data\":[{\"account_id\":\"number\",\"aspect_ratio\":\"string\",\"asset_id\":\"number\",\"asset_img_url\":\"string\",\"asset_name\":\"string\",\"asset_source\":\"number\",\"asset_type\":\"number\",\"audio\":\"number\",\"auto_character_prompt\":\"number\",\"avatar\":\"string\",\"camera_movement\":\"string\",\"create_count\":\"number\",\"create_mode\":\"string\",\"created_at\":\"string\",\"creation_type\":\"number\",\"customer_img_path\":\"string\",\"customer_img_url\":\"string\",\"customer_paths\":{\"agent_info\":\"object\",\"cameo_id_list\":\"object\",\"customer_img_path\":\"string\",\"customer_img_url\":\"string\",\"duration_type\":\"string\",\"ext_info\":\"object\",\"fusion_id_list\":\"object\",\"model_evaluator\":\"string\",\"platform\":\"string\",\"use_api_gen_image\":\"boolean\"},\"cut_time_ms\":\"number\",\"duration\":\"number\",\"email\":\"[REDACTED]\",\"extended\":\"number\",\"feedback_id\":\"number\",\"first_frame\":\"string\",\"img_id\":\"number\",\"img_path\":\"string\",\"img_url\":\"string\",\"is_collected\":\"boolean\",\"is_dislike\":\"number\",\"is_hidden\":\"number\",\"is_remix\":\"boolean\",\"is_sound\":\"number\",\"last_frame\":\"string\",\"likes\":\"number\",\"lip_sync\":\"object\",\"lip_sync_switch\":\"number\",\"lora_weight\":\"number\",\"mask_info\":\"object\",\"media_locked\":\"number\",\"model\":\"string\",\"model_name\":\"string\",\"motion_brush\":\"string\",\"motion_mode\":\"string\",\"multi_shot\":\"number\",\"negative_prompt\":\"string\",\"nick_name\":\"string\",\"off_peak\":\"number\",\"original_sound_switch\":\"number\",\"original_video_id\":\"number\",\"output_height\":\"number\",\"output_width\":\"number\",\"platform\":\"string\",\"preview_mode\":\"number\",\"prompt\":\"string\",\"qualities\":\"object\",\"quality\":\"string\",\"queue_data\":{\"estimated_gen_time\":\"number\",\"processing_start_time\":\"string\",\"queue_count\":\"number\",\"queue_time\":\"number\"},\"relation_type\":\"number\",\"remix_feed_id\":\"number\",\"remove_watermark\":\"number\",\"restyle_id\":\"number\",\"restyle_prompt\":\"string\",\"seed\":\"number\",\"sound_effect_switch\":\"number\",\"style\":\"string\",\"template_i18n_json\":\"string\",\"template_id\":\"number\",\"template_name\":\"string\",\"template_paid\":\"number\",\"template_status\":\"number\",\"template_thumbnail_gif_url\":\"string\",\"template_thumbnail_url\":\"string\",\"template_thumbnail_video_url\":\"string\",\"upscaled\":\"number\",\"url\":\"string\",\"video_created_at\":\"string\",\"video_deleted\":\"number\",\"video_duration\":\"number\",\"video_id\":\"number\",\"video_path\":\"string\",\"video_status\":\"number\",\"webp_url\":\"string\",\"workflow_tag\":\"string\"}],\"has_more\":\"boolean\",\"next_offset\":\"number\",\"web_has_more\":\"boolean\",\"web_next_offset\":\"number\"}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_user_profile_45a238411c",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/pagead/1p-user-list/{id}/",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "www.google.com",
    "queryShape": "async, auid, bg, cid, cv, data, dma, en, fmt, frm, fst, gcd, gtm, guid, hn, ipr, is_vtc, npa, pscdl, random, rcb, ref, rfmt, rmt_tld, tag_exp, tiba, u_h, u_w, url",
    "requestContentType": "",
    "responseContentType": "image/gif",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "user_profile",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 4,
    "sanitizedRequestShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"body\":\"undefined\",\"mimeType\":\"undefined\",\"params\":\"undefined\"},\"query\":{\"ae\":\"string\",\"async\":\"string\",\"auid\":\"string\",\"bg\":\"string\",\"cid\":\"string\",\"cv\":\"string\",\"data\":\"string\",\"dma\":\"string\",\"en\":\"string\",\"fmt\":\"string\",\"frm\":\"string\",\"fst\":\"string\",\"gcd\":\"string\",\"gtm\":\"string\",\"guid\":\"string\",\"hn\":\"string\",\"ipr\":\"string\",\"is_vtc\":\"string\",\"npa\":\"string\",\"pscdl\":\"string\",\"random\":\"string\",\"rcb\":\"string\",\"ref\":\"string\",\"rfmt\":\"string\",\"rmt_tld\":\"string\",\"tag_exp\":\"string\",\"tiba\":\"string\",\"u_h\":\"string\",\"u_w\":\"string\",\"url\":\"string\"}}",
    "sanitizedResponseShape": "{\"content\":{\"body\":{\"R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7\":\"string\"},\"mimeType\":\"string\"},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}]}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_user_profile_48bc811ef3",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/pagead/1p-user-list/{id}/",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "www.google.com.sg",
    "queryShape": "async, auid, bg, cid, cv, data, dma, en, fmt, frm, fst, gcd, gtm, guid, hn, ipr, is_vtc, npa, pscdl, random, rcb, ref, rfmt, rmt_tld, tag_exp, tiba, u_h, u_w, url",
    "requestContentType": "",
    "responseContentType": "image/gif",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "user_profile",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 4,
    "sanitizedRequestShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"body\":\"undefined\",\"mimeType\":\"undefined\",\"params\":\"undefined\"},\"query\":{\"ae\":\"string\",\"async\":\"string\",\"auid\":\"string\",\"bg\":\"string\",\"cid\":\"string\",\"cv\":\"string\",\"data\":\"string\",\"dma\":\"string\",\"en\":\"string\",\"fmt\":\"string\",\"frm\":\"string\",\"fst\":\"string\",\"gcd\":\"string\",\"gtm\":\"string\",\"guid\":\"string\",\"hn\":\"string\",\"ipr\":\"string\",\"is_vtc\":\"string\",\"npa\":\"string\",\"pscdl\":\"string\",\"random\":\"string\",\"rcb\":\"string\",\"ref\":\"string\",\"rfmt\":\"string\",\"rmt_tld\":\"string\",\"tag_exp\":\"string\",\"tiba\":\"string\",\"u_h\":\"string\",\"u_w\":\"string\",\"url\":\"string\"}}",
    "sanitizedResponseShape": "{\"content\":{\"body\":{\"R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7\":\"string\"},\"mimeType\":\"string\"},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}]}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_5a747efaee",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/api/v2/abtest/online/results",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "experiment.pixverse.ai",
    "queryShape": "project-key",
    "requestContentType": "application/json; charset=UTF-8",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 3,
    "sanitizedRequestShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"body\":{\"abtest_lib_version\":\"string\",\"anonymous_id\":\"string\",\"custom_properties\":{},\"login_id\":\"string\",\"param_name\":\"string\",\"platform\":\"string\",\"properties\":{\"$is_first_day\":\"boolean\"}},\"mimeType\":\"string\",\"params\":[]},\"query\":{\"project-key\":\"string\"}}",
    "sanitizedResponseShape": "{\"content\":{\"body\":{\"is_custom_cache\":\"boolean\",\"out_list\":[{\"abtest_experiment_group_id\":\"string\",\"abtest_experiment_id\":\"string\",\"abtest_experiment_result_id\":\"string\",\"abtest_experiment_version\":\"string\",\"cacheable\":\"boolean\",\"experiment_type\":\"string\",\"is_control_group\":\"boolean\",\"is_white_list\":\"boolean\",\"subject_id\":\"string\",\"subject_name\":\"string\",\"variables\":[{\"name\":\"string\",\"type\":\"string\",\"value\":\"string\"}]}],\"results\":[{\"abtest_experiment_group_id\":\"string\",\"abtest_experiment_id\":\"string\",\"abtest_experiment_result_id\":\"string\",\"abtest_experiment_version\":\"string\",\"cacheable\":\"boolean\",\"experiment_type\":\"string\",\"is_control_group\":\"boolean\",\"is_white_list\":\"boolean\",\"subject_id\":\"string\",\"subject_name\":\"string\",\"variables\":[{\"name\":\"string\",\"type\":\"string\",\"value\":\"string\"}]}],\"status\":\"string\"},\"mimeType\":\"string\"},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}]}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_asset_library_81ff94ff3c",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/asset/folder/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "asset_library",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"folders\":[{\"folder_id\":\"number\",\"account_id\":\"number\",\"name\":\"string\",\"asset_count\":\"number\",\"created_at\":\"string\",\"updated_at\":\"string\"}]}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_credit_balance_7263e92cae",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/user/credits",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "credit_balance",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "credit_balance",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"Resp\":{\"credit_daily\":\"number\",\"credit_monthly\":\"number\",\"credit_package\":\"number\",\"high_quality_times\":\"number\",\"has_album_count\":\"number\",\"renewal_credits\":\"number\",\"countdown_remaining_time\":\"number\",\"show_high_price_elite\":\"boolean\",\"agent_template_free_times\":\"number\",\"preview_mode_free_times\":\"number\",\"upscale_preview_free_times\":\"number\",\"is_new_register_user\":\"boolean\",\"is_support_default_720p_in_cur_country\":\"boolean\",\"is_exist_generated_video\":\"boolean\",\"story_free_times\":\"number\",\"is_story_discount\":\"boolean\",\"is_v6_discount\":\"boolean\",\"image_free_365\":\"boolean\",\"remix_promotion_info\":{\"remaining_remix_free_times\":\"number\",\"remix_free_times\":\"number\",\"remix_promotion_mode\":\"number\",\"promotion_start_time\":\"string\",\"promotion_end_time\":\"string\"},\"miniapp_free_trial_remaining\":{\"ad_master\":\"number\",\"promo_mix\":\"number\"},\"promotion_discounts\":\"object\",\"enhance_promotion_info\":{\"remaining_enhance_free_times\":\"number\",\"enhance_free_times\":\"number\",\"promotion_start_time\":\"string\",\"promotion_end_time\":\"string\",\"enhance_promotion_mode\":\"boolean\",\"promotion_discount\":\"number\"},\"create_image_promotion_info\":{\"remaining_free_times\":\"number\",\"total_free_times\":\"number\",\"promotion_start_time\":\"string\",\"promotion_end_time\":\"string\",\"promotion_mode\":\"boolean\"}},\"ErrCode\":\"number\",\"ErrMsg\":\"string\"}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_pricing_d491d4637b",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/creative_platform/toc/members/plan_details",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "application/json",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "pricing",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"string\",\"params\":[],\"body\":{}}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"user_id\":\"[REDACTED]\",\"member_id\":\"number\",\"product_id\":\"number\",\"plan_name\":\"string\",\"next_plan_name\":\"string\",\"next_plan_type\":\"number\",\"current_plan_type\":\"number\",\"type\":\"number\",\"credit_daily\":\"number\",\"credit_daily_gift\":\"number\",\"initial_credit_gift\":\"number\",\"credit_monthly\":\"number\",\"credit_monthly_gift\":\"number\",\"credit_package\":\"number\",\"expired_date\":\"string\",\"price\":\"string\",\"billing_period\":\"number\",\"next_billing_period\":\"number\",\"billing_renewal_date\":\"string\",\"payment\":\"number\",\"invoice_url\":\"string\",\"stripe_bill_url\":\"string\",\"gen_simultaneously\":\"number\",\"allow_fast_mode\":\"number\",\"allow_private_generate\":\"number\",\"remove_watermark\":\"number\",\"allow_purchase_credit\":\"number\",\"sub_order_in_progress\":\"number\",\"allow_effect\":\"number\",\"last_plan_name\":\"string\",\"last_plan_type\":\"number\",\"last_product_id\":\"number\",\"expired_member\":\"number\",\"credits_more\":\"number\",\"album_num\":\"number\",\"batch_generation\":\"number\",\"off_peak\":\"number\",\"off_peak_discount\":\"string\",\"qualities\":[\"string\"],\"cancel_updated_at\":\"string\",\"renewal_retention\":\"number\",\"renewal_price\":\"string\",\"preview_mode\":\"number\",\"preview_mode_discount\":\"string\",\"remaining_days\":\"number\",\"credits_refresh_time\":\"string\",\"daily_credits_refresh_time\":\"string\",\"is_gift_card\":\"boolean\",\"veo_sora_models\":\"number\",\"external_models\":\"object\",\"external_models_discount\":\"string\",\"unlimited_image_models\":\"object\"}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_2ca5e548ff",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/creative_platform/toc/products/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "application/json",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"string\",\"params\":[],\"body\":{}}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":[{\"product_id\":\"number\",\"name\":\"string\",\"member_type\":\"number\",\"product_type\":\"number\",\"price\":\"string\",\"regular_price\":\"string\",\"credit_package\":\"number\",\"billing_period\":\"number\",\"credit_daily_gift\":\"number\",\"gen_simultaneously\":\"number\",\"initial_credit_gift\":\"number\",\"is_new_product\":\"number\",\"instant_generation\":\"number\",\"payment_product_id\":\"string\",\"percent_off\":\"string\",\"price_off\":\"string\",\"qualities\":[\"string\"],\"credits_more\":\"number\",\"album_num\":\"number\",\"batch_generation\":\"number\",\"off_peak\":\"number\",\"v6_c1_promotion\":\"number\",\"seedance_promotion\":\"number\",\"happy_horse_promotion\":\"number\",\"preview_mode\":\"number\",\"off_peak_discount\":\"string\",\"preview_mode_discount\":\"string\",\"original_product_id\":\"number\",\"original_payment_product_id\":\"string\",\"original_price\":\"string\",\"veo_sora_models\":\"number\",\"external_models\":\"object\",\"external_models_discount\":\"string\",\"unlimited_image_models\":\"object\"}]}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_1f38f985d7",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/feedback/tags",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"tags\":[{\"tag_id\":\"number\",\"tag_name\":\"string\",\"i18n_json\":\"string\",\"tag_type\":\"number\"}]}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_88eced8d7b",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/banners",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":[{\"id\":\"number\",\"title\":\"string\",\"content\":\"string\",\"gif_url\":\"string\",\"bg_color\":\"string\",\"button\":\"string\",\"img_url\":\"string\",\"target_path\":\"string\",\"target_url\":\"string\",\"video_url\":\"string\",\"new_feature_guide\":\"string\",\"i18n_json\":\"string\",\"target_member_levels\":\"string\"}]}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_5e61bb90c4",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/showvideos",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":[{\"id\":\"number\",\"title\":\"string\",\"content\":\"string\",\"gif_url\":\"string\",\"bg_color\":\"string\",\"button\":\"string\",\"img_url\":\"string\",\"target_path\":\"string\",\"target_url\":\"string\",\"video_url\":\"string\",\"new_feature_guide\":\"string\",\"i18n_json\":\"string\",\"target_member_levels\":\"string\"}]}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_60580b7271",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/content/categories/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":[{\"id\":\"number\",\"platform\":\"string\",\"category_name\":\"string\",\"parent_id\":\"number\",\"level\":\"number\",\"content_type\":\"string\",\"sort_order\":\"number\",\"show_status\":\"number\",\"ios_show_status\":\"number\",\"android_show_status\":\"number\",\"i18n_json\":\"string\",\"children\":[{\"id\":\"number\",\"platform\":\"string\",\"category_name\":\"string\",\"parent_id\":\"number\",\"level\":\"number\",\"content_type\":\"string\",\"sort_order\":\"number\",\"show_status\":\"number\",\"ios_show_status\":\"number\",\"android_show_status\":\"number\",\"i18n_json\":\"string\"}]}]}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_pricing_bb7a7bbfb5",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/creative_platform/pricing/formulas",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "pricing",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"extend\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"cases\":[{\"compareValue\":\"string\",\"type\":\"string\",\"value\":{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}}],\"switchOn\":{\"name\":\"string\",\"type\":\"string\"},\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"fusion\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"cases\":[{\"compareValue\":\"string\",\"type\":\"string\",\"value\":{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}}],\"switchOn\":{\"name\":\"string\",\"type\":\"string\"},\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"i2i\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"cases\":[{\"compareValue\":\"string\",\"type\":\"string\",\"value\":{\"type\":\"string\",\"value\":\"number\"}}],\"default\":{\"type\":\"string\",\"value\":\"number\"},\"switchOn\":{\"name\":\"string\",\"type\":\"string\"},\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"i2v\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"cases\":[{\"compareValue\":\"string\",\"type\":\"string\",\"value\":{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}}],\"switchOn\":{\"name\":\"string\",\"type\":\"string\"},\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"lipsync\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"cases\":[{\"compareValue\":\"number\",\"type\":\"string\",\"value\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}}],\"default\":{\"cases\":[{\"compareValue\":\"number\",\"type\":\"string\",\"value\":{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}}],\"default\":{\"type\":\"string\",\"value\":\"number\"},\"switchOn\":{\"name\":\"string\",\"type\":\"string\"},\"type\":\"string\"},\"switchOn\":{\"name\":\"string\",\"type\":\"string\"},\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"mimic\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"modify\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"restyle\":{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}],\"type\":\"string\"},\"sound\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"swap\":{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}],\"type\":\"string\"},\"t2i\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"cases\":[{\"compareValue\":\"string\",\"type\":\"string\",\"value\":{\"type\":\"string\",\"value\":\"number\"}}],\"default\":{\"type\":\"string\",\"value\":\"number\"},\"switchOn\":{\"name\":\"string\",\"type\":\"string\"},\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"t2v\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"cases\":[{\"compareValue\":\"string\",\"type\":\"string\",\"value\":{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}}],\"switchOn\":{\"name\":\"string\",\"type\":\"string\"},\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"transition\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"cases\":[{\"compareValue\":\"string\",\"type\":\"string\",\"value\":{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}}],\"switchOn\":{\"name\":\"string\",\"type\":\"string\"},\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"upscale\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"},\"upscale_image\":{\"operator\":\"string\",\"params\":[{\"name\":\"string\",\"params\":[{\"operator\":\"string\",\"params\":[{\"type\":\"string\",\"value\":\"number\"}],\"type\":\"string\"}],\"type\":\"string\"}],\"type\":\"string\"}}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_tts_83e0fb1fed",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/video/tts/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "lip_sync_tts_list",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "tts",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"tts_list\":[{\"speaker_id\":\"string\",\"url\":\"string\",\"display_name\":\"string\",\"img_url\":\"string\"}]}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_restyle_1128468b87",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/creative_platform/restyle/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "restyle_video",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "application/json",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "restyle",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"string\",\"params\":[],\"body\":{\"offset\":\"number\",\"limit\":\"number\"}}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"items\":[{\"restyle_id\":\"number\",\"restyle_tag\":\"string\",\"display_name\":\"string\",\"restyle_prompt\":\"string\",\"thumbnail_path\":\"string\",\"thumbnail_url\":\"string\",\"thumbnail_video_path\":\"string\",\"thumbnail_video_url\":\"string\",\"show_status\":\"string\",\"app_show_status\":\"string\",\"marker\":\"string\",\"display_prompt\":\"string\",\"i18n_json\":{\"de-DE\":{\"display_name\":\"string\"},\"en-US\":{\"display_name\":\"string\"},\"es-ES\":{\"display_name\":\"string\"},\"fr-FR\":{\"display_name\":\"string\"},\"id-ID\":{\"display_name\":\"string\"},\"it-IT\":{\"display_name\":\"string\"},\"ja-JP\":{\"display_name\":\"string\"},\"ko-KR\":{\"display_name\":\"string\"},\"pt-BR\":{\"display_name\":\"string\"},\"ru-RU\":{\"display_name\":\"string\"},\"th-TH\":{\"display_name\":\"string\"},\"tr-TR\":{\"display_name\":\"string\"},\"vi-VN\":{\"display_name\":\"string\"},\"zh-CN\":{\"display_name\":\"string\"}},\"score\":\"number\",\"example_list\":\"string\",\"qualities\":\"object\",\"thumbnail_gif_path\":\"string\",\"thumbnail_gif_url\":\"string\",\"app_thumbnail_path\":\"string\",\"app_thumbnail_url\":\"string\",\"app_thumbnail_video_path\":\"string\",\"app_thumbnail_video_url\":\"string\",\"app_thumbnail_gif_path\":\"string\",\"app_thumbnail_gif_url\":\"string\",\"audio_path\":\"string\",\"audio_url\":\"string\",\"is_del\":\"number\",\"is_pinned\":\"string\",\"created_at\":\"string\",\"updated_at\":\"string\"}],\"next_offset\":\"number\",\"total\":\"number\"}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_c4b322d8d6",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/content/categories/secondary",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "platform, primary_category_id",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{\"primary_category_id\":\"string\",\"platform\":\"string\"},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":[{\"id\":\"number\",\"platform\":\"string\",\"category_name\":\"string\",\"parent_id\":\"number\",\"level\":\"number\",\"content_type\":\"string\",\"sort_order\":\"number\",\"show_status\":\"number\",\"ios_show_status\":\"number\",\"android_show_status\":\"number\",\"i18n_json\":\"string\"}]}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_pricing_aef703d7aa",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/content/template/price/multiplier",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "pricing",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"multipliers\":[{\"quality\":\"string\",\"multiplier\":\"number\"}]}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_c9e3a3adcf",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "GET",
    "path": "/creative_platform/campaign/list",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app-api.pixverse.ai",
    "queryShape": "page_num, page_size, status",
    "requestContentType": "",
    "responseContentType": "application/json",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{\"page_num\":\"string\",\"page_size\":\"string\",\"status\":\"string\"},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":{\"ErrCode\":\"number\",\"ErrMsg\":\"string\",\"Resp\":{\"total\":\"number\",\"list\":[]}}}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_35e2046a39",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/cdn-cgi/rum",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "app.pixverse.ai",
    "queryShape": "",
    "requestContentType": "application/json",
    "responseContentType": "text/plain",
    "statusCodesObserved": [
      204
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"string\",\"params\":[],\"body\":{\"memory\":{},\"resources\":[],\"referrer\":\"string\",\"eventType\":\"number\",\"firstPaint\":\"number\",\"firstContentfulPaint\":\"number\",\"startTime\":\"number\",\"versions\":{\"fl\":\"string\",\"js\":\"string\",\"timings\":\"number\"},\"pageloadId\":\"string\",\"location\":\"string\",\"nt\":\"string\",\"timingsV2\":{\"nextHopProtocol\":\"string\",\"domainLookupStart\":\"number\",\"domainLookupEnd\":\"number\",\"connectStart\":\"number\",\"connectEnd\":\"number\",\"requestStart\":\"number\",\"responseStart\":\"number\",\"responseEnd\":\"number\",\"domInteractive\":\"number\",\"domComplete\":\"number\",\"loadEventStart\":\"number\",\"loadEventEnd\":\"number\",\"finalResponseHeadersStart\":\"number\",\"firstInterimResponseStart\":\"number\",\"transferSize\":\"number\",\"decodedBodySize\":\"number\"},\"dt\":\"string\",\"siteToken\":\"string\",\"st\":\"number\"}}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":\"undefined\"}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_d8c8986da0",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/pagead/form-data/{id}",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "www.google.com",
    "queryShape": "ae, auid, dma, frm, gcd, gcs, gtm, npa, pscdl, rcb, tag_exp",
    "requestContentType": "",
    "responseContentType": "text/html",
    "statusCodesObserved": [
      200
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{\"gtm\":\"string\",\"gcs\":\"string\",\"gcd\":\"string\",\"dma\":\"string\",\"tag_exp\":\"string\",\"rcb\":\"string\",\"npa\":\"string\",\"frm\":\"string\",\"pscdl\":\"string\",\"ae\":\"string\",\"auid\":\"string\"},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":\"undefined\"}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  },
  {
    "id": "pixverse_web_unknown_3a0e550955",
    "providerId": "pixverse_web",
    "providerGroup": "pixverse",
    "providerSource": "web",
    "method": "POST",
    "path": "/ccm/form-data/{id}",
    "baseUrlEnvKey": "PIXVERSE_WEB_BASE_URL",
    "docsUrl": "manual-har:b5c2c0bc2b96",
    "authRequired": true,
    "capability": "unknown",
    "requestSchema": "Sanitized HAR-derived request shape. Verify manually before implementation.",
    "responseSchema": "Sanitized HAR-derived response shape. Verify manually before implementation.",
    "implemented": false,
    "stability": "experimental_web",
    "notes": "Observed from a user-provided HAR file. Automatic web actions remain disabled.",
    "host": "www.google.com",
    "queryShape": "ae, auid, dma, ec_mode, ecsid, em, frm, gcd, gcs, gtm, npa, pscdl, rcb, tag_exp",
    "requestContentType": "",
    "responseContentType": "text/plain",
    "statusCodesObserved": [
      204
    ],
    "operationGuess": "unknown",
    "lastObservedAt": "2026-06-02T12:45:01.782Z",
    "sampleCount": 1,
    "sanitizedRequestShape": "{\"query\":{\"gtm\":\"string\",\"gcs\":\"string\",\"gcd\":\"string\",\"dma\":\"string\",\"tag_exp\":\"string\",\"rcb\":\"string\",\"npa\":\"string\",\"frm\":\"string\",\"ae\":\"string\",\"pscdl\":\"string\",\"auid\":\"string\",\"ec_mode\":\"string\",\"em\":\"string\",\"ecsid\":\"string\"},\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"postData\":{\"mimeType\":\"undefined\",\"params\":\"undefined\",\"body\":\"undefined\"}}",
    "sanitizedResponseShape": "{\"headers\":[{\"name\":\"string\",\"value\":\"string\"}],\"content\":{\"mimeType\":\"string\",\"body\":\"undefined\"}}",
    "sourceHarFingerprint": "b5c2c0bc2b96",
    "source": "har"
  }
];

export function replacePixVerseWebObservedEndpointManifest(endpoints: ProviderEndpointManifestEntry[]) {
  pixverseWebObservedEndpointManifest.splice(0, pixverseWebObservedEndpointManifest.length, ...endpoints);
}
